create table assessment
(
    id           bigint generated by default as identity,
    closed_date  timestamp,
    created_by   varchar(255),
    created_date timestamp,
    name         varchar(255),
    open         boolean not null,
    version      integer,
    primary key (id)
);

create table assessment_item
(
    id            bigint generated by default as identity,
    seen          boolean not null,
    version       integer,
    assessment_id bigint,
    asset_id      bigint,
    primary key (id)
);

create table asset
(
    id           bigint generated by default as identity,
    description  varchar(255),
    device_id    varchar(255),
    inventory_id varchar(255),
    manufacturer varchar(255),
    part_id      varchar(255),
    source       text,
    unit         varchar(255),
    version      integer,
    primary key (id)
);

create table note
(
    id                 bigint generated by default as identity,
    created_by         varchar(255),
    created_date       timestamp,
    last_modified_by   varchar(255),
    last_modified_date timestamp,
    text               text,
    type               varchar(32),
    version            integer,
    assessment_item_id bigint,
    asset_id           bigint not null,
    primary key (id)
);

alter table assessment_item
    add constraint UQ_assessment_asset unique (assessment_id, asset_id);

alter table assessment_item
    add constraint FK_assessment_item_assessment
        foreign key (assessment_id)
            references assessment;

alter table assessment_item
    add constraint FK_assessment_item_asset
        foreign key (asset_id)
            references asset;

alter table note
    add constraint FK_note_assessment_item
        foreign key (assessment_item_id)
            references assessment_item;

alter table note
    add constraint FK_note_asset
        foreign key (asset_id)
            references asset;